### PR TITLE
Add support for pymatgen BandStructure and CompleteDos

### PR DESCRIPTION
**Pull request by zooks97**
Support for `pymatgen.electronic_structure.bandstructure.BandStructure` and `pymatgen.electronic_structure.dos.CompleteDos` objects.

Both helpers are fairly straightforward, and by-and-large they are the same as for pymatgen `Structure` objects.

However, there is a bug(?) in the [`as_dict`](https://github.com/materialsproject/pymatgen/blob/6737f23caaf646cc58425561cf08339acf77b396/pymatgen/electronic_structure/bandstructure.py#L127) method of `pymatgen.electronic_structure.bandstructure.Kpoint` which causes the `'kpoints'` and `'labels_dict'` values of `BandStructure.as_dict()` to contain numpy numerical types, which mincepy doesn't know how to store.

So, I hacked together a recursive cleaning function for the `BandStructure.as_dict()`  and also left two more direct lines of code as comments which also fix the issue. 

Any comments on how to move forward on this front?

With respect to the `CompleteDosHelper`, pymatgen `CompleteDos` objects are _not_ designed to be created manually, rather they are almost always generated directly from VASP output or retrieved from the Materials Project. Therefore, it seems quite difficult to implement tests without including a JSON file containing a `CompleteDos` as a test fixture.

I'd also appreciate comments in this respect.

### CODE REVIEW

**Comment by muhrin** [comment]
Woah, nice, sorry I hadn't seen this until now!

I see now the problem with the numpy numbers in the band structure.  I think what you've done is the right way to go.

Gotcha regarding the `CompleteDos`.  Yeah, if it's not too hard including a `JSON` that in can read to bootstrap creating one would be a good way to test.  If you think it's not too hard just create a `res` (for resources) folder in `test` and dump it in there.  Then put the `res` folder in the `MANIFEST.in`, I think something like `recursive-include test/res *` should work.

**Comment by zooks97** [comment]
I managed to get a [fix](https://github.com/materialsproject/pymatgen/pull/2113) for the `BandStructure` dictification merged into pymatgen quite quickly, so in the future that issue will be fixed. However, for backwards compatibility, we'll have to keep the recursive cleaner (and maybe add a check for pymatgen version so we don't do more work than necessary). 

I'll throw in a `JSON` for the `CompleteDos` testing and mark the pull as ready to review when its done.

Cheers!

**Comment by muhrin** [comment]
Fantastic, glad you got in in to PYG.  So just to check, both with the old and the new merged fix the mincePy will get the same thing back i.e. a list containing standard python floats?

**Comment by zooks97** [comment]
Yes, mincePy should always get the same thing back: only standard python lists, floats, etc.

The recursive cleaner will make sure that mincePy gets standard python floats, and it should work with old pymatgen versions (that have some extraneous numpy floats) and with future pymatgen versions with the fix (i.e. the `as_dict()` result won't have any numpy floats, only python floats).

However, with future pymatgen versions we won't need to do the cleaning, and it would be better _not_ to do it to save the cost of the recursive function looking over everything.

**Comment by muhrin** [comment]
Great, that's what I thought.  Then if saving performance becomes an issue we can always put in a version check and ship the recursive algorithm.

**Comment by muhrin** [comment]
One more thing occurred to me. Do you know what the license is for things downloaded form the MP?  I don't just want to be careful in case we violate a license term by including it in our repo.

**Comment by zooks97** [comment]
It looks like the `Dos` family of objects from pymatgen have a similar issue to what `Kpoint` had, so I've added a call to the cleaner in the `save_instance_state` method of `CompleteDosHelper`. I'll do another pull request to pymatgen.

I added a `JSON` file for the `CompleteDos` of Si and a test for saving `CompleteDos` objects.

Should be ready for review!

**Comment by zooks97** [comment]
Fix for the underlying DOS issue is [here](https://github.com/materialsproject/pymatgen/pull/2119)

**Comment by muhrin** [comment]
Sweet.  Any idea about the MP data license?

**Comment by zooks97** [comment]
What we need to do isn't 100% clear. It's licensed under a [Creative Commons Attribution 4.0 License](https://creativecommons.org/licenses/by/4.0/), and in their terms they link on the works [proper attribution](https://materialsproject.org/citing).

To retrieve the data, I used pymatgen and the Materials API, so maybe we include the citations for those and a link to the proper attribution / citing page above?

**Comment by muhrin** [comment]
Could you pull in this: https://github.com/muhrin/mincepy_sci/tree/changes to this PR?  I don't know why but I can't create a PR against your branch...

I think that should cover the licensing issues.

**Comment by zooks97** [comment]
Should be in!

**Review by muhrin — APPROVED** [review]

**Comment by muhrin** [comment]
Top work lad

**Pull request merged**
